### ISSUE TITLE
Top level class signals used by different hierarchy levels naming inconsistency

### ISSUE THREAD

**Issue by hackfin** [myhdl/myhdl#286]
This is a very late report, as I've been working with a stable 0.9 branch for a long time. Not sure if I'm making a mistake.
When using a signal class whose members route to different levels in the hierarchy, the top level signals are expanded inconsistently. This broke my interface after aca9332:

```
entity Unit is
    port (
        clk: in std_logic;
        tap_reset: in std_logic;
        dummy0_tap_emuir: in unsigned(7 downto 0);
        dummy0_tap_emureq: in std_logic;
        tap_emuack: in std_logic;
        tap_emuexec: in std_logic
    );
end entity Unit;

```

Expected:
```
...
        tap_reset: in std_logic;
        tap_emuir: in unsigned(7 downto 0);
...

```

Test case for new @block decorator policy attached. The inconsistent name mangling happens in 'legacy' instancing mode as well, with expansion to
```
        d_tap_emuir: in unsigned(7 downto 0);
```

instead.

[test-hierarchy.py.gz](https://github.com/myhdl/myhdl/files/2649047/test-hierarchy.py.gz)

**Comment by cfelton** [comment]
@hackfin thanks for the input, this is a known limitation or "feature" of the python compiler.  As you point out it is under investigation.  We will have to add code to expand the top-level interfaces rather than relying on the python compiler, since it isn't concerned with maintaining a consistent reference.
